### ISSUE TITLE
Backup/recovery mechanisms.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/terraform-nomad-postgres#10]

**Comment by pdmthorsrud** [comment]
https://www.linode.com/docs/databases/postgresql/how-to-back-up-your-postgresql-database/

**Comment by zhenik** [comment]
https://hub.docker.com/_/postgres -> Where to Store Data

**Comment by zhenik** [comment]
resolved here https://github.com/fredrikhgrelland/terraform-nomad-postgres/pull/17
