### ISSUE TITLE
Move fetching of data in vault to nomad's job-file

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/terraform-nomad-postgres#18]
Right now we are using terraform-resources to fetch data from vault (specifically username and password):
https://github.com/fredrikhgrelland/terraform-nomad-postgres/blob/ae78b48fbd54e039f42194ae75e4364b33de21a9/example/main.tf#L1-L3
and 
https://github.com/fredrikhgrelland/terraform-nomad-postgres/blob/ae78b48fbd54e039f42194ae75e4364b33de21a9/example/main.tf#L16-L17

This should be done via [templates inside the nomad-job instead](https://www.nomadproject.io/docs/integrations/vault-integration). Nomad-job's templating uses [consul-template](https://github.com/hashicorp/consul-template) which will dynamically update files if any of its references change.  

Summary: the creation of data in vault should still be done via terraform resources, but the fetching of it should be done via nomad-templating, so that it'll dynamically update.

**Comment by zhenik** [comment]
Possible problems:
- how to extract user & pass as output terraform variables (variables exist only in rendered nomad-job)?
- how to use conditional rendering (if input variables `user;pass` not provided as input variables?)

**Comment by zhenik** [comment]
Example from presto module https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/conf/nomad/presto.hcl#L327

**Comment by claesgill** [comment]
I think we can close this issue due to PR #47. Or WDYT @zhenik  @pdmthorsrud ?

EDIT: Clicked the wrong button ... 🤦

**Comment by pdmthorsrud** [comment]
Yup, you're right!
